package com.takesome.springsuite.module;

public enum SuiteModuleActivationStatus {
    ACTIVE,
    DISABLED_DUPLICATE_ID,
    DISABLED_MISSING_DEPENDENCY,
    DISABLED_DEPENDENCY_VERSION_MISMATCH,
    DISABLED_DEPENDENCY_CYCLE,
    DISABLED_INCOMPATIBLE_SUITE_API,
    DISABLED_UNSUPPORTED_ISOLATION,
    DISABLED_INVALID_MANIFEST
}
